config/routes.rb
Newton::Application.routes.draw do
  devise_for :users

  resources :newts
  
  match '/users/:id/dashboard' => 'users#dashboard', :as => 'users_dashboard'

  match '/newt/:id.json' => 'newts#remote', :as => 'get_newton', :via => "get"

  match '/newts(/:id)(/:secret)/edit' => 'newts#edit', :as => 'edit_newton'
  match '/add_editor_field' => 'newts#add_editor_field', :as => 'add_editor_field'
  match '/newts(/:id)(/:secret)(/:editor)/remove_editor' => 'newts#remove_editor', :as => 'remove_editor'
  match '/scripts/newton' => 'javascripts#newton', :as => 'get_newton_script'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "newts#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_newts
  has_many :newts, :through => :user_newts
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable, :recoverable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  validates :email, :uniqueness => true, :presence => true
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
    
  scope :with_newts_owned, joins(:newts).where('user_newts.owner = ?', true) 
  
  class << self  
    def get_newts
      newts = {}
      user_newts = UserNewt.find_by_user_id(id)
      user_newts.each do |n|
        newt = Newts.find(n.newt_id)
        newts << newt
      end
      newts
    end
  
    def define_users_params(params)
      user_options = params
      temporary_password = random_password
      user_options['password'] = temporary_password
      user_options['password_salt'] = temporary_password
      user_options['password_confirmation'] = temporary_password
      user_options
    end

    def create_temprary_account(user_params)
      User.create!(define_users_params(user_params))
    end

    def random_password
      Digest::SHA1.hexdigest("--#{Time.now.to_s}--newton--")[0,8]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    #facebook login: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
    
    @newts = current_user.newts.order(:updated_at).page params[:page]
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @newts }
    end
  end
  
end

app/views/users/dashboard.html.erb
<h1>My Newts</h1>

<% if @newts.present? %>
  <table class="zebra-striped">
    <tr>
      <th>ID</th>
      <th>Content</th>
      <th>Editors</th>
      <th>Locations</th>
      <th>Requests</th>
      <th>Actions</th>
    </tr>
  <% @newts.each do |newt| %>
    <tr>
      <td><small><%= newt.uniq_id %></small></td>
      <td>
        <div id="newt-content">
          <small><%= newt.title %></small>
          <blockquote><p><%= raw(newt.content) %></p></blockquote>
        </div>
      </td>
      <td>
        <%= newt.user_newts.count %>
      </td>
      <td>
        <%= newt.locations.count %>
      </td>
      <td>
        <%= newt.locations.sum(:request_count) %>
      </td>
      <td>
        <span class="label success"><%= link_to 'Edit', edit_newton_url(:id => newt.uniq_id, :secret => newt.uniq_secret) %></span>
        <span class="label"><%= link_to 'Details', newt %></span>
        <% if Newt.owner(newt) == current_user %>
        <span class="label important"><%= link_to 'Destroy', newt, :confirm => 'Are you sure?', :method => :delete %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>
  <%= paginate @newts %>
<% else %>
  <h6>You don't have any yet, why don't you make one?</h6>
  <%= link_to 'Create a Newt', new_newt_url, :class => 'btn success' %>
<% end %>