config/routes.rb
Newton::Application.routes.draw do
  devise_for :users

  resources :newts
  
  match '/users/:id/dashboard' => 'users#dashboard', :as => 'users_dashboard'

  match '/newt/:id.json' => 'newts#remote', :as => 'get_newton', :via => "get"

  match '/newts(/:id)(/:secret)/edit' => 'newts#edit', :as => 'edit_newton'
  match '/add_editor_field' => 'newts#add_editor_field', :as => 'add_editor_field'
  match '/newts(/:id)(/:secret)(/:editor)/remove_editor' => 'newts#remove_editor', :as => 'remove_editor'
  match '/scripts/newton' => 'javascripts#newton', :as => 'get_newton_script'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "newts#index"

end

app/models/newt.rb
class Newt < ActiveRecord::Base
  has_many :user_newts, :dependent => :destroy
  has_many :locations, :dependent => :destroy

  before_create :generate_random_ids, :generate_title

  validates :content, :presence => true
  #validates :uniq_id, :uniqueness => true, :presence => true
  
  scope :count_editors, joins(:user_newts).count() 
  
  def generate_random_ids
     self.uniq_id = SecureRandom.hex(5)
     self.uniq_secret = SecureRandom.hex(12)
  end 
  
  def generate_title
     self.title = ActionController::Base.helpers.strip_tags(content)[0..30] if self.title.blank?
  end 
  
  def send_content_editor_link_mail(user, newt)
    NewtonMailer.content_editor_link(user, newt).deliver
  end

  class << self  
    def owner(newt)
      user_newt = UserNewt.find(:first, :conditions => ['newt_id = ? AND owner = ?', newt.id, true])
      newt_owner = (User.find(user_newt.user_id) rescue false)
    end
  end
end

app/controllers/newts_controller.rb
class NewtsController < ApplicationController

  def index
    @newt = Newt.new
    get_email

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @newt = Newt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @newt }
    end
  end
  
  def remove_editor
    @newt = Newt.find_by_uniq_id(params[:id])
    @editor = UserNewt.first(:conditions => ['user_id = ? AND newt_id = ?', params[:editor], @newt.id])
    @editor.destroy

    redirect_to edit_newton_url(:id => @newt.uniq_id, :secret => @newt.uniq_secret)
  end  
  
  def remote
    @newt = Newt.find_by_uniq_id(params[:id])
        
    location = Location.first(:conditions => ['newt_id = ? AND url = ?', @newt.id, params[:url]])
    if location.present?
      location.update_attributes(:request_count => (location.request_count.to_i + 1))
    else
      location = Location.new({:newt_id => @newt.id, :ip => request.remote_ip, :url => params[:url], :page_title => params[:title], :request_count => 1}).save
    end

    respond_to do |format|
      #format.html # show.html.erb
      format.json  { 
        render :json =>  @newt.content.to_json, :callback => params[:callback], :content_type => 'application/json' 
      }
    end
  end

  def new
    @newt = Newt.new
    get_email

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @newt }
    end
  end

  def edit
    @newt = Newt.find_by_uniq_id(params[:id])
    usernewt = UserNewt.find_by_newt_id(@newt.id)
    @user = User.find(usernewt.user_id)
  end
  
  def new_or_existing?(email)
    user = User.find_by_email(email)
    unless user.present?
      user = User.create_temprary_account({:email => email})
      if user.valid?
        user.save
      else
        @newt.errors.add 'Email', "Address must be valid"
        render :action => "new"
        return false
      end
    end
    user
  end

  def create
    @newt = Newt.new(params[:newt])
    
    user = ( current_user.present? ? current_user : new_or_existing?(params[:user][:email]) )
    unless user.present? 
      return
    end
    
    if params[:add_editor].present?
      additional = []
      params[:add_editor].each do |e|
        add_user = new_or_existing?(e)
        if add_user
          additional << add_user
        else
          return
        end
      end
    end
    
    respond_to do |format|
      if @newt.save
        usernewt = UserNewt.new(:user_id => user.id, :newt_id => @newt.id, :owner => true).save
        if additional.present?
          additional.each do |a|
            UserNewt.new(:user_id => a.id, :newt_id => @newt.id).save
          end
        end
        @newt.send_content_editor_link_mail(user, @newt)
        format.html { redirect_to(@newt, :notice => 'Newt was successfully created.') }
        format.xml  { render :xml => @newt, :status => :created, :location => @newt }
      else
        get_email
        format.html { render :action => "new" }
        format.xml  { render :xml => @newt.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @newt = Newt.find(params[:id])
    
    if params[:add_editor].present?
      additional = []
      params[:add_editor].each do |e|
        add_user = new_or_existing?(e)
        if add_user
          additional << add_user
        else
          return
        end
      end
    end

    respond_to do |format|
      if @newt.update_attributes(params[:newt])
        if additional.present?
          additional.each do |a|
            UserNewt.new(:user_id => a.id, :newt_id => @newt.id).save
          end
        end
        format.html { redirect_to(@newt, :notice => 'Newt was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @newt.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @newt = Newt.find(params[:id])
    @newt.destroy

    respond_to do |format|
      format.html { redirect_to(users_dashboard_url) }
      format.xml  { head :ok }
    end
  end

  def get_email
    if current_user
      @email = current_user.email
    elsif (params[:user][:email] rescue false)
      @email = params[:user][:email]
    else
      @email = nil
    end
  end
  
  def add_editor_field
    render :layout => false
  end
end

app/views/newts/_form.html.erb
<% content_for :javascript_includes do %>
<script>
  function add_lorem(){
    var lorem = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel est leo. Praesent in justo quis tortor sollicitudin hendrerit sit amet vel quam. Nulla sit amet tellus et dui faucibus fermentum.\n';
    var textarea = jQuery("#newt_content");
    var content = textarea.val();
    textarea.val( content + lorem );
    return false;
  }
  jQuery(document).ready(function() {
    jQuery('#newt_content').ckeditor();
    jQuery('#lorem').click(function() {
      add_lorem();
    });
    jQuery('#add_editor').bind("click", function(event) {
      jQuery.get('<%= add_editor_field_url %>', function(data) {
        jQuery('#new_editors').append(data);
      });
    });
  });
</script>
<%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>
<% end %>

<% content_for :alert_content do %>
  <% if @newt.errors.any? %>
    <div class="alert-message block-message error fade in" data-alert="alert">
      <a class="close" href="#">×</a>
      <strong><%= pluralize(@newt.errors.count, "error") %> prohibited this newt from being saved:</strong>
      <ul>
      <% @newt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for(@newt) do |f| %>
  <% if @newt.uniq_id.present? %>
  <%= f.hidden_field :uniq_id %>
  <% end %>
  <div class="clearfix">
    <%= f.label :title %><br />
    <div class="input"><%= f.text_field :title, :class => 'span10' %></div>
  </div>
  <div class="clearfix">
    <%= f.label :content %>
    <div class="input">
      <%= f.text_area :content, :toolbar => 'Simple' %>
      <span class="help-block"><span class="label"><a href="javascript: void(0);" id="lorem">Add Lorem Ipsum</a></span></span>
    </div>
  </div>
  
<% if @newt.user_newts.count > 1 %>
  <div class="clearfix">
    <%= f.label 'Editors' %>
    <div class="input">
      <ul>
      <% @newt.user_newts.each do |u| %>
        <% if u.user.id != current_user.id %>
        <li><%= raw(u.user.email) %> <span class="label important"><%= link_to 'Remove', remove_editor_url(:id => @newt.uniq_id, :secret => @newt.uniq_secret, :editor => u.user.id), :confirm => 'Are you sure?', :method => :delete %></span></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>  
  
  <% if current_user.present? -%>
    <% if (Newt.owner(@newt) == current_user rescue false) || @newt.id.blank? -%>
      <%= hidden_field :user, :email, :value => @email %>
      <div class="clearfix">
        <div class="input">
          <span class="label warning"><a href="#" id="add_editor">Add Another Editor</a></span>
        </div>
      </div>
      <div id="new_editors"></div>
    <% end -%>
  <% else -%>
    <div class="clearfix">
      <label for="editor">Editor</label><br />
      <div class="input">
        <div class="input-prepend">
          <span class="add-on">@</span>
          <%= text_field :user, :email, :value => @email %><br/>
          <span class="help-inline">This email address will receive an email with a link to edit this content</span>
        </div>
      </div>
    </div>
  <% end -%>
  <div class="actions">
    <% unless @newt.id.blank? -%>
      <%= link_to 'Cancel', @newt, :class => 'btn secondary' %>
    <% end -%>
    <%= f.submit 'Submit', :class => 'btn primary' %>
  </div>
<% end %>

app/views/newts/add_editor_field.html.erb
<div class="clearfix">
  <label for="editor">Editor</label><br />
  <div class="input">
    <div class="input-prepend">
      <span class="add-on">@</span>
      <input type="text" name="add_editor[]"><br/>
      <span class="help-inline">This email address will receive an email with a link to edit this content</span>
    </div>
  </div>
</div>

app/views/newts/edit.html.erb
<h1>Editing <%= @newt.title %></h1>

<% if params[:id].present? && params[:secret].present? %>
  <% if params[:id] == @newt.uniq_id && params[:secret] == @newt.uniq_secret %>
    <%= render 'form' %>
  <% else %>
    <h3>ID or Secret is incorrect.  You cannot edit this newt without the correct ID and Secret</h3>
  <% end %>
<% else %>
  <h3>ID or Secret missing.  You cannot edit this newt without them</h3>
<% end %>

<% content_for :nav_action_buttons do %>
<% end %>

app/views/newts/index.html.erb
<% if current_user.present? -%>
  <h1>Welcome Back</h1>
<% else -%>
  <h1>Welcome to Newton!</h1>
<% end -%>

<h3>Get Started, create a Newt</h3>

<%= render 'form' %>

<% content_for :nav_action_buttons do %>
<% end %>

app/views/newts/new.html.erb
<h1>New Newt</h1>

<%= render 'form' %>

<% content_for :nav_action_buttons do -%>
<% end -%>

app/views/newts/remote.html.erb
<%= @newt.content %>

app/views/newts/show.html.erb
<% content_for :javascript_includes do %>
<script>
  jQuery(document).ready(function() {
            $(function () {
              $("a[rel=twipsy]").twipsy({
                live: true,
                placement: 'right'
              })
            })
  });
</script>
<% end %>

<h2><%= @newt.title %></h2>

<%= link_to('Edit', edit_newton_url(@newt.uniq_id, :secret => @newt.uniq_secret), :class => 'btn primary topright') %>
<%= link_to('Back to List', users_dashboard_url(current_user.id), :class => 'btn secondary topright') %>

<p>
  <h3>ID</h3>
    <pre class="prettyprint"><%= @newt.uniq_id %></pre>
</p>

<p>
  <h3>Insert Code</h3>
  <span class="help-inline">Insert the following code into any webpage, and BAM! editable content.</span>
  <pre class="prettyprint">
    <%= '<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>' %>
    <%= '<script src="' %><%= get_newton_script_url %><%= '" type="text/javascript"></script>' %>
    <%= '<div id="newt-' %><%= @newt.uniq_id %><%= '"></div>' -%>
  </pre>
</p>

<p>
  <h3>Last Updated</h3>
  <%= @newt.updated_at.to_s(:long) -%>
</p>

<% if @newt.user_newts.count > 1 %>
<p>
<h3>Editors</h3>
<ul>
<% @newt.user_newts.each do |u| %>
  <% if u.user.id != current_user.id %>
  <li><%= raw(u.user.email) %></li>
  <% end %>
<% end %>
</ul>
<% end %>

<% if @newt.locations.count >= 1 %>
<p>
<h3>Locations</h3>
<ul id="locations">
<% @newt.locations.order("updated_at DESC").each do |l| %>
  <li>The page, <a rel="twipsy" href="<%= l.url -%>" data-original-title="<%= l.url -%>"><%= l.page_title.present? ? l.page_title : 'Unknown' -%></a>, requested this newt <%= l.request_count -%> times, most recently at <%= l.updated_at.to_s(:long) -%></li>
<% end %>
</ul>
<% end %>

<p>
  <h3>Here's your glorious content, by the way</h3>
  <p class="span10">
    <div class="well"><%= raw(@newt.content) %></div>
  </p>
</p>