config/routes.rb
Newton::Application.routes.draw do
  devise_for :users

  resources :newts
  
  match '/users/:id/dashboard' => 'users#dashboard', :as => 'users_dashboard'

  match '/newt/:id.json' => 'newts#remote', :as => 'get_newton', :via => "get"

  match '/newts(/:id)(/:secret)/edit' => 'newts#edit', :as => 'edit_newton'
  match '/add_editor_field' => 'newts#add_editor_field', :as => 'add_editor_field'
  match '/newts(/:id)(/:secret)(/:editor)/remove_editor' => 'newts#remove_editor', :as => 'remove_editor'
  match '/scripts/newton' => 'javascripts#newton', :as => 'get_newton_script'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "newts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NEWTON</title>
  <link rel="shortcut icon" type="image/png" href="/images/newt.png">
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

  <%= javascript_include_tag 'jquery.min' %>
  
  <script type="text/javascript" src="/javascripts/ckeditor/ckeditor.js"></script>
  <script type="text/javascript" src="/javascripts/ckeditor/adapters/jquery.js"></script>
  
  <!-- compiled CSS with 'less' -->
  <link rel="stylesheet/less" type="text/css" href="/stylesheets/lib/bootstrap.less">
  <%= javascript_include_tag 'less-1.1.3.min' %>
  <%= stylesheet_link_tag 'style', 'prettify' %>

  <%= javascript_include_tag 'bootstrap-alerts', 'bootstrap-dropdown', 'bootstrap-twipsy', 'prettify/prettify' %>
  <%= yield(:javascript_includes) %>
</head>

<body onload="prettyPrint()" class="<%= params[:controller] + '_' + params[:action] %>">
  
  <div class="topbar">
    <div class="topbar-inner">
      <div class="container">
        <h3><a href="/">NEWTON</a></h3>
        <ul class="nav">
          <li class="active"><a href="/">Home</a></li>
          <li><%= link_to 'Create a Newt', new_newt_path %></li>
        </ul>
        <!-- form action="" class="pull-left">
          <input type="text" placeholder="Search">
        </form -->
        <% if current_user.present? %>
        <ul class="nav secondary-nav">
          <li class="dropdown" data-dropdown="dropdown" >
            <a class="dropdown-toggle" href="#">My Account</a>
            <ul class="dropdown-menu">
              <li><a href="<%= users_dashboard_path(current_user.id) %>">My Newts</a></li>
              <li><a href="<%= users_dashboard_path(current_user.id) %>">Account Settings</a></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
        <% else %>
        <ul class="nav secondary-nav">
          <li><a href="<%= new_user_session_path %>">Log In</a></li>
        </ul>
        <% end %>
      </div>
    </div><!-- /topbar-inner -->
  </div><!-- .topbar -->
  
  <% if :nav_action_buttons -%>
  <div id="secondary_nav">
    <ul class="pills">
    <%= yield(:nav_action_buttons) %>
    </ul>
  </div>
  <% end -%>
    
<div class="container"> 
  
  <div class="content">
  
  <% if notice.present?%>
    <div id="flash">
      <div class="alert-message warning fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= notice %></p>
      </div>
    </div>
  <% end %>
  <% if alert.present? %>
    <div id="flash">
      <div class="alert-message error fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= alert %></p>
      </div>
    </div>
  <% end %>
  
  <%= yield(:alert_content) %>

  <%= yield %>
  
  </div><!-- .content --> 
  
</div><!-- .container-fluid -->  
  


</body>
</html>